### ISSUE TITLE
requesting TGT fails with >= pyasn1 0.2.1 

### ISSUE THREAD

**Issue by aus** [skelsec/PyKerberoast#1]
I haven't had time to dive into the pyasn1 documentation, but it seems there were some breaking changes in pyasn1 0.2.x. Reverting to 0.1.9 with `pip install pyasn1==0.1.9` fixes the issue.
```
$ pip show pyasn1
Name: pyasn1
Version: 0.2.3
Summary: ASN.1 types and codecs
Home-page: https://github.com/etingof/pyasn1
Author: Ilya Etingof <etingof@gmail.com>
Author-email: etingof@gmail.com
License: BSD
Location: /usr/local/lib/python2.7/dist-packages
Requires:

$ python kerberoastv2.py -a the.domain.com -b "DC=the,DC=domain,DC=com" -d domain -u user -v
[+]Starting...
Password:
[+]Fetching SPN accounts from AD
[+]Got 1SPN accounts!
[+]Requesting TGT tciket ticket ticket...
Traceback (most recent call last):
  File "kerberoastv2.py", line 62, in <module>
    tgt, cipher, key, sessionKey = getTGT(user, password, domain, AD_address)
  File "/store/user/src/PyKerberoast/getTGS.py", line 9, in getTGT
    tgt, cipher, key, sessionKey = getKerberosTGT(userName, password, domain, '', '', kdcHost=AD_address)
  File "/usr/local/lib/python2.7/dist-packages/impacket/krb5/kerberosv5.py", line 257, in getKerberosTGT
    asRep = decoder.decode(tgt, asn1Spec = AS_REP())[0]
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 908, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 67, in valueDecoder
    value, _ = decodeFun(head, asn1Spec, tagSet, length)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 908, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 358, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 908, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 67, in valueDecoder
    value, _ = decodeFun(head, asn1Spec, tagSet, length)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 908, in __call__
    stGetValueDecoder, self, substrateFun
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 101, in valueDecoder
    return self._createComponent(asn1Spec, tagSet, value), tail
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/codec/ber/decoder.py", line 39, in _createComponent
    return asn1Spec.clone(value)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 285, in clone
    return self.__class__(value, tagSet, subtypeSpec, namedValues)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/univ.py", line 70, in __init__
    self, value, tagSet, subtypeSpec
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 177, in __init__
    self._verifySubtypeSpec(value)
  File "/usr/local/lib/python2.7/dist-packages/pyasn1/type/base.py", line 45, in _verifySubtypeSpec
    raise c('%s at %s' % (i, self.__class__.__name__))
pyasn1.type.error.ValueConstraintError: ConstraintsIntersection(ConstraintsIntersection(), ConstraintsUnion(SingleValueConstraint(10), SingleValueConstraint(12))) failed at: ValueConstraintError('ConstraintsUnion(SingleValueConstraint(10), SingleValueConstraint(12)) failed at: ValueConstraintError(\'all of (SingleValueConstraint(10), SingleValueConstraint(12)) failed for "11"\',)',) at Integer

$ pip install pyasn1==0.1.9
Collecting pyasn1==0.1.9
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Installing collected packages: pyasn1
  Found existing installation: pyasn1 0.2.1
    Uninstalling pyasn1-0.2.1:
      Successfully uninstalled pyasn1-0.2.1
Successfully installed pyasn1-0.1.9

$ python kerberoastv2.py -a the.domain.com -b "DC=the,DC=domain,DC=com" -d domain -u user -v
[+]Starting...
Password:
[+]Fetching SPN accounts from AD
[+]Got 1SPN accounts!
[+]Requesting TGT tciket ticket ticket...
[+]Fetching TGS tickets for all users, might take a while...
[+]Got 1 valid TGS tickets to crack..
<ticket redacted>
[+]Done!
```

**Comment by CaledoniaProject** [comment]
You should submit a pull request for a `requirements.txt`

**Comment by skelsec** [comment]
Yeah, this is one of the many resons I'm ditching pyasn1, and this script as well :)
Please consider using the new [kerberoast package](https://github.com/skelsec/kerberoast)
